-- Sample Articles Data for Restaurants
-- GuidePlatform Syria-Turkey Business Guide Platform
-- Created: 2025-01-27

-- Sample data for Aleppo Kebap House (978bea96-ec7f-461b-aefa-deaac61df09e)
INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Geleneksel Halep Kebap Yapımının Sırları',
    'Halep kebap, Suriye mutfağının en önemli lezzetlerinden biridir. Bu geleneksel yemek, özel baharatlar ve taze malzemelerle hazırlanır. Kebap yapımında kullanılan et, özenle seçilmiş kuzu etidir ve özel soslarla marine edilir. Geleneksel Halep kebap ve mezelerinin sunulduğu restoranımızda, bu lezzetli yemeği en otantik haliyle sunuyoruz. Kebap yapımında kullanılan baharatlar arasında kimyon, kişniş, zerdeçal ve özel Halep baharat karışımı bulunur. Et, odun ateşinde yavaşça pişirilir ve bu sayede eşsiz lezzetini kazanır. Yanında sunulan mezeler arasında humus, babagannuş, patlıcan salatası ve taze ekmek bulunur. Bu geleneksel lezzet, yüzyıllardır süregelen tariflerle hazırlanır ve her lokmada Suriye mutfağının zengin kültürünü hissettirir.',
    'Halep kebap yapımının sırları ve geleneksel tarifleri hakkında detaylı bilgi. Özel baharatlar ve pişirme teknikleri ile hazırlanan bu eşsiz lezzet hakkında her şey.',
    NULL, -- Fotoğraf verisi buraya eklenebilir
    NULL, -- Küçük resim verisi buraya eklenebilir
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL, -- Kategori ID'si buraya eklenebilir
    true, -- Öne çıkan makale
    true, -- Yayınlanmış
    CURRENT_TIMESTAMP,
    1250,
    'Geleneksel Halep Kebap Yapımının Sırları - Aleppo Kebap House',
    'Halep kebap yapımının sırları, geleneksel tarifler ve özel baharatlar hakkında detaylı bilgi. Suriye mutfağının en önemli lezzetlerinden biri olan Halep kebap hakkında her şey.',
    'geleneksel-halep-kebap-yapiminin-sirlari',
    'food',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Suriye Mutfağında Meze Kültürü',
    'Suriye mutfağında meze kültürü, yemek deneyiminin ayrılmaz bir parçasıdır. Mezeler, ana yemekten önce sunulan küçük porsiyonlu lezzetlerdir ve genellikle ekmek ile birlikte tüketilir. Geleneksel Halep kebap ve mezelerinin sunulduğu restoranımızda, en otantik meze çeşitlerini bulabilirsiniz. Humus, nohut püresi, tahin, zeytinyağı ve limon suyu ile hazırlanır. Babagannuş, közlenmiş patlıcan, tahin, sarımsak ve limon suyu ile yapılır. Fattoush salatası, taze sebzeler, kızarmış ekmek parçaları ve sumak ile hazırlanır. Tabbouleh, bulgur, maydanoz, domates, salatalık ve zeytinyağı ile yapılan geleneksel bir salatadır. Bu mezeler, Suriye mutfağının zengin lezzet dünyasını yansıtır ve her biri kendine özgü aromaya sahiptir.',
    'Suriye mutfağında meze kültürü ve geleneksel meze çeşitleri hakkında detaylı bilgi. Humus, babagannuş, fattoush ve tabbouleh gibi popüler mezeler.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    false,
    true,
    CURRENT_TIMESTAMP,
    890,
    'Suriye Mutfağında Meze Kültürü - Geleneksel Lezzetler',
    'Suriye mutfağında meze kültürü, geleneksel meze çeşitleri ve yapım teknikleri hakkında detaylı bilgi. Humus, babagannuş ve diğer popüler mezeler.',
    'suriye-mutfaginda-meze-kulturu',
    'culture',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

-- Sample data for Manbij Lokantası (005542a0-ce29-4aa9-b71e-442dd007de67)
INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Suriye Mutfağının En Güzel Örnekleri: Humus ve Falafel',
    'Suriye mutfağının en güzel örneklerini sunan lokantamızda, geleneksel tariflerle hazırlanan yemeklerimizi deneyebilirsiniz. Humus, nohut püresi, tahin, zeytinyağı ve limon suyu ile hazırlanan geleneksel bir mezedir. Bu lezzetli yemek, yüzyıllardır Suriye mutfağının vazgeçilmez bir parçası olmuştur. Falafel, nohut, fasulye, soğan, sarımsak ve özel baharatlarla hazırlanan kızarmış köftelerdir. Bu geleneksel lezzet, hem vejetaryen hem de et yiyenler tarafından sevilir. Humus ve falafel, genellikle taze ekmek ile birlikte sunulur ve her lokmada Suriye mutfağının zengin lezzet dünyasını hissettirir. Bu yemekler, sadece lezzetli olmakla kalmaz, aynı zamanda besleyici değerleri de yüksektir.',
    'Suriye mutfağının en güzel örnekleri olan humus ve falafel hakkında detaylı bilgi. Geleneksel tarifler ve yapım teknikleri.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    true,
    true,
    CURRENT_TIMESTAMP,
    1100,
    'Suriye Mutfağının En Güzel Örnekleri: Humus ve Falafel',
    'Suriye mutfağının en güzel örnekleri olan humus ve falafel hakkında detaylı bilgi. Geleneksel tarifler, yapım teknikleri ve lezzet sırları.',
    'suriye-mutfaginin-en-guzel-ornekleri-humus-ve-falafel',
    'food',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Günlük Öğle Menüsü: Suriye Mutfağından Seçmeler',
    'Günlük öğle menümüzde yeni seçenekler eklendi. Her gün farklı ana yemek ve çorba seçenekleriyle hizmet veriyoruz. Suriye mutfağının en güzel örneklerini sunan lokantamızda, geleneksel tariflerle hazırlanan yemeklerimizi deneyebilirsiniz. Öğle menümüzde genellikle mercimek çorbası, nohut çorbası veya domates çorbası bulunur. Ana yemek olarak kuzu eti, tavuk eti veya balık çeşitleri sunulur. Yanında pilav, bulgur pilavı veya patates kızartması servis edilir. Salata olarak fattoush, tabbouleh veya mevsim salatası bulunur. Tatlı olarak baklava, künefe veya sütlaç sunulur. Bu menü, Suriye mutfağının zengin lezzet dünyasını yansıtır ve her gün farklı seçeneklerle zenginleştirilir.',
    'Günlük öğle menüsünde sunulan Suriye mutfağından seçmeler. Her gün farklı ana yemek, çorba ve tatlı seçenekleri.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    false,
    true,
    CURRENT_TIMESTAMP,
    650,
    'Günlük Öğle Menüsü: Suriye Mutfağından Seçmeler',
    'Günlük öğle menüsünde sunulan Suriye mutfağından seçmeler. Her gün farklı ana yemek, çorba ve tatlı seçenekleri ile zengin menü.',
    'gunluk-ogle-menusu-suriye-mutfagindan-secmeler',
    'menu',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

-- Sample data for Azaz Sofra (f60578b0-ca95-4b3f-b2e9-b66679e8f88c)
INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Ev Yapımı Suriye Yemekleri: Annelerimizin Tarifleri',
    'Ev yapımı Suriye yemekleri sunan aile restoranımızda, annelerimizin tarifleriyle hazırlanan geleneksel lezzetleri bulabilirsiniz. Bu yemekler, yüzyıllardır aile içinde aktarılan tariflerle hazırlanır ve her lokmada sıcaklık ve sevgi hissettirir. Özellikle mercimek çorbası, kırmızı mercimek, soğan, sarımsak ve özel baharatlarla hazırlanır. Kısır, bulgur, domates, salatalık, maydanoz ve zeytinyağı ile yapılan geleneksel bir salatadır. Bu yemekler, sadece lezzetli olmakla kalmaz, aynı zamanda besleyici değerleri de yüksektir. Ev yapımı Suriye yemekleri, geleneksel pişirme teknikleri kullanılarak hazırlanır ve her biri kendine özgü aromaya sahiptir. Bu lezzetler, Suriye kültürünün zengin mirasını yansıtır ve aile bağlarını güçlendirir.',
    'Ev yapımı Suriye yemekleri ve annelerimizin tarifleri hakkında detaylı bilgi. Mercimek çorbası, kısır ve diğer geleneksel lezzetler.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    true,
    true,
    CURRENT_TIMESTAMP,
    980,
    'Ev Yapımı Suriye Yemekleri: Annelerimizin Tarifleri',
    'Ev yapımı Suriye yemekleri ve annelerimizin tarifleri hakkında detaylı bilgi. Mercimek çorbası, kısır ve diğer geleneksel lezzetler.',
    'ev-yapimi-suriye-yemekleri-annelerimizin-tarifleri',
    'home',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Aile Paketi Kampanyası: 4 Kişilik Özel Menü',
    '4 kişilik aile paketimizde ana yemek, çorba, salata ve tatlı dahil sadece 150 TL! Bu özel paket, ailece keyifli bir akşam yemeği için idealdir. Ev yapımı Suriye yemekleri sunan aile restoranımızda, annelerimizin tarifleriyle hazırlanan geleneksel lezzetleri bulabilirsiniz. Aile paketimizde genellikle mercimek çorbası, kuzu eti ana yemek, kısır salata ve baklava tatlısı bulunur. Bu paket, Suriye mutfağının en popüler lezzetlerini içerir ve aile bağlarını güçlendirir. Rezervasyon için bizi arayın ve bu özel fırsatı kaçırmayın. Aile paketimiz, hem lezzetli hem de ekonomik bir seçenektir.',
    '4 kişilik aile paketi kampanyası hakkında detaylı bilgi. Ana yemek, çorba, salata ve tatlı dahil özel fiyat.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    false,
    true,
    CURRENT_TIMESTAMP,
    750,
    'Aile Paketi Kampanyası: 4 Kişilik Özel Menü',
    '4 kişilik aile paketi kampanyası hakkında detaylı bilgi. Ana yemek, çorba, salata ve tatlı dahil özel fiyat ile ailece keyifli yemek.',
    'aile-paketi-kampanyasi-4-kisilik-ozel-menu',
    'family',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

-- Sample data for Afrin Lezzet (f76e31c4-3e4e-4a58-a5bb-3a57597603f6)
INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Modern Suriye Mutfağı Konsepti: Geleneksel Lezzetler, Çağdaş Sunum',
    'Modern Suriye mutfağı konseptli restoranımızda, geleneksel lezzetleri çağdaş sunum teknikleriyle birleştiriyoruz. Bu yaklaşım, Suriye mutfağının zengin lezzet dünyasını modern gastronomi ile buluşturur. Özel şef menümüzü deneyin ve farkı hissedin. Geleneksel tarifler, modern pişirme teknikleri kullanılarak hazırlanır ve her yemek kendine özgü sunumla servis edilir. Bu konsept, hem geleneksel lezzetleri korur hem de çağdaş gastronomi trendlerini yansıtır. Modern Suriye mutfağı, geleneksel malzemeleri kullanarak yeni lezzetler yaratır ve her yemekte sürpriz sunar. Bu yaklaşım, Suriye mutfağının geleceğini şekillendirir ve uluslararası standartlarda hizmet verir.',
    'Modern Suriye mutfağı konsepti ve geleneksel lezzetlerin çağdaş sunumu hakkında detaylı bilgi. Özel şef menüsü ve modern gastronomi.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    true,
    true,
    CURRENT_TIMESTAMP,
    1350,
    'Modern Suriye Mutfağı Konsepti: Geleneksel Lezzetler, Çağdaş Sunum',
    'Modern Suriye mutfağı konsepti ve geleneksel lezzetlerin çağdaş sunumu hakkında detaylı bilgi. Özel şef menüsü ve modern gastronomi teknikleri.',
    'modern-suriye-mutfagi-konsepti-geleneksel-lezzetler-cagdas-sunum',
    'chef',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Özel Etkinlik: Suriye Gecesi - Canlı Müzik ve Dans Gösterileri',
    'Her Cuma akşamı Suriye Gecesi etkinliğimizde canlı müzik eşliğinde geleneksel dans gösterileri ve özel menü seçenekleri sunuyoruz. Bu özel etkinlik, Suriye kültürünün zengin mirasını yansıtır ve unutulmaz anılar yaratır. Canlı müzik performansları, geleneksel Suriye enstrümanları kullanılarak gerçekleştirilir. Dans gösterileri, profesyonel dansçılar tarafından sergilenir ve her gösteri kendine özgü hikayeyi anlatır. Özel menü seçenekleri, geleneksel Suriye lezzetlerini modern sunum teknikleriyle birleştirir. Bu etkinlik, sadece yemek deneyimi değil, aynı zamanda kültürel bir deneyimdir. Rezervasyon gerekli olup, sınırlı sayıda misafir kabul edilir.',
    'Her Cuma akşamı Suriye Gecesi etkinliği. Canlı müzik, dans gösterileri ve özel menü seçenekleri ile kültürel deneyim.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    false,
    true,
    CURRENT_TIMESTAMP,
    920,
    'Özel Etkinlik: Suriye Gecesi - Canlı Müzik ve Dans Gösterileri',
    'Her Cuma akşamı Suriye Gecesi etkinliği. Canlı müzik, dans gösterileri ve özel menü seçenekleri ile kültürel deneyim.',
    'ozel-etkinlik-suriye-gecesi-canli-muzik-ve-dans-gosterileri',
    'event',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

-- Sample data for Jarabulus Mutfak (7fb6d642-528b-4dcd-8e58-785b7c9542f4)
INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Otantik Suriye Lezzetleri: Baklava ve Künefe Yapımı',
    'Otantik Suriye lezzetleri ve tatlıları sunan restoranımızda, geleneksel tariflerle hazırlanan baklava ve künefe çeşitlerimizi deneyin. Bu geleneksel tatlılar, yüzyıllardır Suriye mutfağının vazgeçilmez bir parçası olmuştur. Baklava, ince yufka katmanları arasına fındık, fıstık veya ceviz yerleştirilerek hazırlanır. Her katman tereyağı ile yağlanır ve fırında altın sarısı renginde pişirilir. Üzerine şerbet dökülür ve soğumaya bırakılır. Künefe, kadayıf hamuru, peynir ve tereyağı ile hazırlanan geleneksel bir tatlıdır. Bu tatlı, özel künefe tavasında pişirilir ve üzerine şerbet dökülür. Her iki tatlı da, geleneksel tariflerle hazırlanır ve her lokmada Suriye mutfağının zengin lezzet dünyasını hissettirir.',
    'Otantik Suriye lezzetleri olan baklava ve künefe yapımı hakkında detaylı bilgi. Geleneksel tarifler ve pişirme teknikleri.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    true,
    true,
    CURRENT_TIMESTAMP,
    1050,
    'Otantik Suriye Lezzetleri: Baklava ve Künefe Yapımı',
    'Otantik Suriye lezzetleri olan baklava ve künefe yapımı hakkında detaylı bilgi. Geleneksel tarifler ve pişirme teknikleri.',
    'otantik-suriye-lezzetleri-baklava-ve-kunefe-yapimi',
    'dessert',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Kahve ve Çay Kültürü: Geleneksel Suriye İçecekleri',
    'Geleneksel Suriye kahvesi ve çay çeşitlerimizle birlikte sunulan tatlılarımızı deneyin. Suriye kahve kültürü, yüzyıllardır süregelen geleneksel yöntemlerle hazırlanır. Bu kahve, özel kahve potlarında pişirilir ve genellikle şeker ile servis edilir. Nane çayı, taze nane yaprakları ile hazırlanan geleneksel bir içecektir ve özellikle yaz aylarında serinletici etkiye sahiptir. Türk kahvesi, ince öğütülmüş kahve çekirdekleri ile hazırlanır ve geleneksel fincanlarda servis edilir. Bu içecekler, baklava ve künefe gibi geleneksel tatlılarla birlikte sunulur ve her yudumda Suriye kültürünün zengin mirasını hissettirir. Kahve ve çay kültürü, Suriye toplumunda sosyal bağları güçlendirir ve her içecek kendine özgü hikayeyi anlatır.',
    'Geleneksel Suriye kahvesi ve çay çeşitleri hakkında detaylı bilgi. Nane çayı, Türk kahvesi ve tatlılarla sunumu.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    false,
    true,
    CURRENT_TIMESTAMP,
    780,
    'Kahve ve Çay Kültürü: Geleneksel Suriye İçecekleri',
    'Geleneksel Suriye kahvesi ve çay çeşitleri hakkında detaylı bilgi. Nane çayı, Türk kahvesi ve tatlılarla sunumu.',
    'kahve-ve-cay-kulturu-geleneksel-suriye-icecekleri',
    'coffee',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

-- Additional sample articles for different scenarios

-- Draft article example (not published yet)
INSERT INTO articles (
    id,
    title,
    content,
    excerpt,
    photo,
    thumbnail,
    photo_content_type,
    author_id,
    category_id,
    is_featured,
    is_published,
    published_at,
    view_count,
    seo_title,
    seo_description,
    slug,
    icon,
    row_created_date,
    row_updated_date,
    row_is_active,
    row_is_deleted,
    auth_user_id,
    create_user_id,
    auth_customer_id,
    update_user_id
) VALUES (
    gen_random_uuid(),
    'Yakında: Online Sipariş Sistemi ve Mobil Uygulama',
    'Çok yakında online sipariş sistemimiz devreye girecek. Mobil uygulamamızı indirerek evinizden sipariş verebileceksiniz. Bu sistem, müşterilerimize daha kolay ve hızlı hizmet sunmayı amaçlar. Online sipariş sistemi, mevcut menü seçeneklerini içerir ve özel kampanyalar sunar. Mobil uygulama, kullanıcı dostu arayüz ile kolay kullanım sağlar. Bu sistem, restoranımızın dijital dönüşümünü tamamlar ve müşteri memnuniyetini artırır. Online sipariş sistemi, geleneksel lezzetleri modern teknoloji ile buluşturur.',
    'Çok yakında online sipariş sistemi ve mobil uygulama. Evinizden sipariş verme imkanı ve dijital dönüşüm.',
    NULL,
    NULL,
    'image/jpeg',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    NULL,
    false,
    false, -- Henüz yayınlanmadı
    NULL,
    0,
    'Yakında: Online Sipariş Sistemi ve Mobil Uygulama',
    'Çok yakında online sipariş sistemi ve mobil uygulama. Evinizden sipariş verme imkanı ve dijital dönüşüm.',
    'yakinda-online-siparis-sistemi-ve-mobil-uygulama',
    'mobile',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true,
    false,
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '19a8b428-a57e-4a24-98e3-470258d3d83e',
    '72c54b1a-8e1c-45ea-8edd-b5da1091e325',
    '19a8b428-a57e-4a24-98e3-470258d3d83e'
);

-- Comments in Turkish as requested:
-- Bu dosya, GuidePlatform için örnek makale verilerini içerir
-- Her restoran için farklı türde makaleler tanımlanmıştır
-- Makaleler farklı durumlarda (yayınlanmış, taslak, öne çıkan) örneklenmiştir
-- Her makale için uygun ikonlar, SEO bilgileri ve slug'lar belirlenmiştir
-- Fotoğraf alanları NULL olarak bırakılmış, gerçek uygulamada binary veri eklenebilir
-- Makale içerikleri detaylı ve bilgilendirici olarak hazırlanmıştır
